/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletTransactionStatusRouteImport } from './routes/wallet-transaction-status'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UfcRouteImport } from './routes/ufc'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TennisRouteImport } from './routes/tennis'
import { Route as SportsbettingRouteImport } from './routes/sportsbetting'
import { Route as ReceiptPreviewRouteImport } from './routes/receipt-preview'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewsRouteImport } from './routes/news'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as GeneralBettingRulesRouteImport } from './routes/general-betting-rules'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GameExitRouteImport } from './routes/game-exit'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BoxingRouteImport } from './routes/boxing'
import { Route as BettingRouteImport } from './routes/betting'
import { Route as BetHistoryRouteImport } from './routes/bet-history'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as UfcIndexRouteImport } from './routes/ufc.index'
import { Route as TennisIndexRouteImport } from './routes/tennis.index'
import { Route as PromotionsIndexRouteImport } from './routes/promotions.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as KycIndexRouteImport } from './routes/kyc.index'
import { Route as BoxingIndexRouteImport } from './routes/boxing.index'
import { Route as BasketballIndexRouteImport } from './routes/basketball.index'
import { Route as WalletTransactionsRouteImport } from './routes/wallet.transactions'
import { Route as TennisMatchesRouteImport } from './routes/tennis.matches'
import { Route as TennisIdRouteImport } from './routes/tennis/$Id'
import { Route as SportsbettingSplatRouteImport } from './routes/sportsbetting/$'
import { Route as PromotionsIdRouteImport } from './routes/promotions.$id'
import { Route as PlayGameNameRouteImport } from './routes/play.$gameName'
import { Route as NotificationsIdRouteImport } from './routes/notifications.$id'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as KycVerifyRouteImport } from './routes/kyc.verify'
import { Route as IndexMatchesRouteImport } from './routes/index.matches'
import { Route as IndexGameIdRouteImport } from './routes/index.$gameId'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as BetHistoryTicketIdRouteImport } from './routes/bet-history.$ticketId'
import { Route as BasketballMatchesRouteImport } from './routes/basketball.matches'
import { Route as BasketballIdRouteImport } from './routes/basketball/$Id'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthPhoneSignInRouteImport } from './routes/auth/phone-sign-in'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as TennisTournamentTournamentIdRouteImport } from './routes/tennis.tournament.$tournamentId'
import { Route as NewsSlugOgRouteImport } from './routes/news.$slug.og'
import { Route as IndexTournamentTournamentIdRouteImport } from './routes/index.tournament.$tournamentId'
import { Route as BasketballTournamentTournamentIdRouteImport } from './routes/basketball.tournament.$tournamentId'

const WalletTransactionStatusRoute = WalletTransactionStatusRouteImport.update({
  id: '/wallet-transaction-status',
  path: '/wallet-transaction-status',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UfcRoute = UfcRouteImport.update({
  id: '/ufc',
  path: '/ufc',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisRoute = TennisRouteImport.update({
  id: '/tennis',
  path: '/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsbettingRoute = SportsbettingRouteImport.update({
  id: '/sportsbetting',
  path: '/sportsbetting',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPreviewRoute = ReceiptPreviewRouteImport.update({
  id: '/receipt-preview',
  path: '/receipt-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralBettingRulesRoute = GeneralBettingRulesRouteImport.update({
  id: '/general-betting-rules',
  path: '/general-betting-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GameExitRoute = GameExitRouteImport.update({
  id: '/game-exit',
  path: '/game-exit',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxingRoute = BoxingRouteImport.update({
  id: '/boxing',
  path: '/boxing',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingRoute = BettingRouteImport.update({
  id: '/betting',
  path: '/betting',
  getParentRoute: () => rootRouteImport,
} as any)
const BetHistoryRoute = BetHistoryRouteImport.update({
  id: '/bet-history',
  path: '/bet-history',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const UfcIndexRoute = UfcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UfcRoute,
} as any)
const TennisIndexRoute = TennisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TennisRoute,
} as any)
const PromotionsIndexRoute = PromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const KycIndexRoute = KycIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KycRoute,
} as any)
const BoxingIndexRoute = BoxingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoxingRoute,
} as any)
const BasketballIndexRoute = BasketballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BasketballRoute,
} as any)
const WalletTransactionsRoute = WalletTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => WalletRoute,
} as any)
const TennisMatchesRoute = TennisMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => TennisRoute,
} as any)
const TennisIdRoute = TennisIdRouteImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => TennisRoute,
} as any)
const SportsbettingSplatRoute = SportsbettingSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SportsbettingRoute,
} as any)
const PromotionsIdRoute = PromotionsIdRouteImport.update({
  id: '/promotions/$id',
  path: '/promotions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameNameRoute = PlayGameNameRouteImport.update({
  id: '/play/$gameName',
  path: '/play/$gameName',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIdRoute = NotificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotificationsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const KycVerifyRoute = KycVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => KycRoute,
} as any)
const IndexMatchesRoute = IndexMatchesRouteImport.update({
  id: '/index/matches',
  path: '/index/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexGameIdRoute = IndexGameIdRouteImport.update({
  id: '/index/$gameId',
  path: '/index/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const BetHistoryTicketIdRoute = BetHistoryTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => BetHistoryRoute,
} as any)
const BasketballMatchesRoute = BasketballMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => BasketballRoute,
} as any)
const BasketballIdRoute = BasketballIdRouteImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => BasketballRoute,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPhoneSignInRoute = AuthPhoneSignInRouteImport.update({
  id: '/auth/phone-sign-in',
  path: '/auth/phone-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisTournamentTournamentIdRoute =
  TennisTournamentTournamentIdRouteImport.update({
    id: '/tournament/$tournamentId',
    path: '/tournament/$tournamentId',
    getParentRoute: () => TennisRoute,
  } as any)
const NewsSlugOgRoute = NewsSlugOgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => NewsSlugRoute,
} as any)
const IndexTournamentTournamentIdRoute =
  IndexTournamentTournamentIdRouteImport.update({
    id: '/index/tournament/$tournamentId',
    path: '/index/tournament/$tournamentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BasketballTournamentTournamentIdRoute =
  BasketballTournamentTournamentIdRouteImport.update({
    id: '/tournament/$tournamentId',
    path: '/tournament/$tournamentId',
    getParentRoute: () => BasketballRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/bet-history': typeof BetHistoryRouteWithChildren
  '/betting': typeof BettingRoute
  '/boxing': typeof BoxingRouteWithChildren
  '/faq': typeof FaqRoute
  '/faqs': typeof FaqsRoute
  '/favorites': typeof FavoritesRoute
  '/game-exit': typeof GameExitRoute
  '/games': typeof GamesRoute
  '/general-betting-rules': typeof GeneralBettingRulesRoute
  '/kyc': typeof KycRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/sportsbetting': typeof SportsbettingRouteWithChildren
  '/tennis': typeof TennisRouteWithChildren
  '/terms': typeof TermsRoute
  '/ufc': typeof UfcRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/wallet': typeof WalletRouteWithChildren
  '/wallet-transaction-status': typeof WalletTransactionStatusRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/phone-sign-in': typeof AuthPhoneSignInRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/basketball/matches': typeof BasketballMatchesRoute
  '/bet-history/$ticketId': typeof BetHistoryTicketIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/index/matches': typeof IndexMatchesRoute
  '/kyc/verify': typeof KycVerifyRoute
  '/news/$slug': typeof NewsSlugRouteWithChildren
  '/notifications/$id': typeof NotificationsIdRoute
  '/play/$gameName': typeof PlayGameNameRoute
  '/promotions/$id': typeof PromotionsIdRoute
  '/sportsbetting/$': typeof SportsbettingSplatRoute
  '/tennis/$Id': typeof TennisIdRoute
  '/tennis/matches': typeof TennisMatchesRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/basketball/': typeof BasketballIndexRoute
  '/boxing/': typeof BoxingIndexRoute
  '/kyc/': typeof KycIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/tennis/': typeof TennisIndexRoute
  '/ufc/': typeof UfcIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/basketball/tournament/$tournamentId': typeof BasketballTournamentTournamentIdRoute
  '/index/tournament/$tournamentId': typeof IndexTournamentTournamentIdRoute
  '/news/$slug/og': typeof NewsSlugOgRoute
  '/tennis/tournament/$tournamentId': typeof TennisTournamentTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bet-history': typeof BetHistoryRouteWithChildren
  '/betting': typeof BettingRoute
  '/faq': typeof FaqRoute
  '/faqs': typeof FaqsRoute
  '/favorites': typeof FavoritesRoute
  '/game-exit': typeof GameExitRoute
  '/games': typeof GamesRoute
  '/general-betting-rules': typeof GeneralBettingRulesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/sportsbetting': typeof SportsbettingRouteWithChildren
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/wallet-transaction-status': typeof WalletTransactionStatusRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/phone-sign-in': typeof AuthPhoneSignInRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/basketball/matches': typeof BasketballMatchesRoute
  '/bet-history/$ticketId': typeof BetHistoryTicketIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/index/matches': typeof IndexMatchesRoute
  '/kyc/verify': typeof KycVerifyRoute
  '/news/$slug': typeof NewsSlugRouteWithChildren
  '/notifications/$id': typeof NotificationsIdRoute
  '/play/$gameName': typeof PlayGameNameRoute
  '/promotions/$id': typeof PromotionsIdRoute
  '/sportsbetting/$': typeof SportsbettingSplatRoute
  '/tennis/$Id': typeof TennisIdRoute
  '/tennis/matches': typeof TennisMatchesRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/basketball': typeof BasketballIndexRoute
  '/boxing': typeof BoxingIndexRoute
  '/kyc': typeof KycIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/news': typeof NewsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/promotions': typeof PromotionsIndexRoute
  '/tennis': typeof TennisIndexRoute
  '/ufc': typeof UfcIndexRoute
  '/videos': typeof VideosIndexRoute
  '/basketball/tournament/$tournamentId': typeof BasketballTournamentTournamentIdRoute
  '/index/tournament/$tournamentId': typeof IndexTournamentTournamentIdRoute
  '/news/$slug/og': typeof NewsSlugOgRoute
  '/tennis/tournament/$tournamentId': typeof TennisTournamentTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/bet-history': typeof BetHistoryRouteWithChildren
  '/betting': typeof BettingRoute
  '/boxing': typeof BoxingRouteWithChildren
  '/faq': typeof FaqRoute
  '/faqs': typeof FaqsRoute
  '/favorites': typeof FavoritesRoute
  '/game-exit': typeof GameExitRoute
  '/games': typeof GamesRoute
  '/general-betting-rules': typeof GeneralBettingRulesRoute
  '/kyc': typeof KycRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/sportsbetting': typeof SportsbettingRouteWithChildren
  '/tennis': typeof TennisRouteWithChildren
  '/terms': typeof TermsRoute
  '/ufc': typeof UfcRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/wallet': typeof WalletRouteWithChildren
  '/wallet-transaction-status': typeof WalletTransactionStatusRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/phone-sign-in': typeof AuthPhoneSignInRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/basketball/matches': typeof BasketballMatchesRoute
  '/bet-history/$ticketId': typeof BetHistoryTicketIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/index/matches': typeof IndexMatchesRoute
  '/kyc/verify': typeof KycVerifyRoute
  '/news/$slug': typeof NewsSlugRouteWithChildren
  '/notifications/$id': typeof NotificationsIdRoute
  '/play/$gameName': typeof PlayGameNameRoute
  '/promotions/$id': typeof PromotionsIdRoute
  '/sportsbetting/$': typeof SportsbettingSplatRoute
  '/tennis/$Id': typeof TennisIdRoute
  '/tennis/matches': typeof TennisMatchesRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/basketball/': typeof BasketballIndexRoute
  '/boxing/': typeof BoxingIndexRoute
  '/kyc/': typeof KycIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/tennis/': typeof TennisIndexRoute
  '/ufc/': typeof UfcIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/basketball/tournament/$tournamentId': typeof BasketballTournamentTournamentIdRoute
  '/index/tournament/$tournamentId': typeof IndexTournamentTournamentIdRoute
  '/news/$slug/og': typeof NewsSlugOgRoute
  '/tennis/tournament/$tournamentId': typeof TennisTournamentTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/basketball'
    | '/bet-history'
    | '/betting'
    | '/boxing'
    | '/faq'
    | '/faqs'
    | '/favorites'
    | '/game-exit'
    | '/games'
    | '/general-betting-rules'
    | '/kyc'
    | '/news'
    | '/notifications'
    | '/privacy-policy'
    | '/receipt-preview'
    | '/sportsbetting'
    | '/tennis'
    | '/terms'
    | '/ufc'
    | '/videos'
    | '/wallet'
    | '/wallet-transaction-status'
    | '/auth'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/phone-sign-in'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$slug'
    | '/basketball/$Id'
    | '/basketball/matches'
    | '/bet-history/$ticketId'
    | '/game/$gameId'
    | '/index/$gameId'
    | '/index/matches'
    | '/kyc/verify'
    | '/news/$slug'
    | '/notifications/$id'
    | '/play/$gameName'
    | '/promotions/$id'
    | '/sportsbetting/$'
    | '/tennis/$Id'
    | '/tennis/matches'
    | '/wallet/transactions'
    | '/basketball/'
    | '/boxing/'
    | '/kyc/'
    | '/missions/'
    | '/news/'
    | '/notifications/'
    | '/promotions/'
    | '/tennis/'
    | '/ufc/'
    | '/videos/'
    | '/basketball/tournament/$tournamentId'
    | '/index/tournament/$tournamentId'
    | '/news/$slug/og'
    | '/tennis/tournament/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/bet-history'
    | '/betting'
    | '/faq'
    | '/faqs'
    | '/favorites'
    | '/game-exit'
    | '/games'
    | '/general-betting-rules'
    | '/privacy-policy'
    | '/receipt-preview'
    | '/sportsbetting'
    | '/terms'
    | '/wallet'
    | '/wallet-transaction-status'
    | '/auth'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/phone-sign-in'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$slug'
    | '/basketball/$Id'
    | '/basketball/matches'
    | '/bet-history/$ticketId'
    | '/game/$gameId'
    | '/index/$gameId'
    | '/index/matches'
    | '/kyc/verify'
    | '/news/$slug'
    | '/notifications/$id'
    | '/play/$gameName'
    | '/promotions/$id'
    | '/sportsbetting/$'
    | '/tennis/$Id'
    | '/tennis/matches'
    | '/wallet/transactions'
    | '/basketball'
    | '/boxing'
    | '/kyc'
    | '/missions'
    | '/news'
    | '/notifications'
    | '/promotions'
    | '/tennis'
    | '/ufc'
    | '/videos'
    | '/basketball/tournament/$tournamentId'
    | '/index/tournament/$tournamentId'
    | '/news/$slug/og'
    | '/tennis/tournament/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/basketball'
    | '/bet-history'
    | '/betting'
    | '/boxing'
    | '/faq'
    | '/faqs'
    | '/favorites'
    | '/game-exit'
    | '/games'
    | '/general-betting-rules'
    | '/kyc'
    | '/news'
    | '/notifications'
    | '/privacy-policy'
    | '/receipt-preview'
    | '/sportsbetting'
    | '/tennis'
    | '/terms'
    | '/ufc'
    | '/videos'
    | '/wallet'
    | '/wallet-transaction-status'
    | '/auth/_layout'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/phone-sign-in'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$slug'
    | '/basketball/$Id'
    | '/basketball/matches'
    | '/bet-history/$ticketId'
    | '/game/$gameId'
    | '/index/$gameId'
    | '/index/matches'
    | '/kyc/verify'
    | '/news/$slug'
    | '/notifications/$id'
    | '/play/$gameName'
    | '/promotions/$id'
    | '/sportsbetting/$'
    | '/tennis/$Id'
    | '/tennis/matches'
    | '/wallet/transactions'
    | '/basketball/'
    | '/boxing/'
    | '/kyc/'
    | '/missions/'
    | '/news/'
    | '/notifications/'
    | '/promotions/'
    | '/tennis/'
    | '/ufc/'
    | '/videos/'
    | '/basketball/tournament/$tournamentId'
    | '/index/tournament/$tournamentId'
    | '/news/$slug/og'
    | '/tennis/tournament/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BasketballRoute: typeof BasketballRouteWithChildren
  BetHistoryRoute: typeof BetHistoryRouteWithChildren
  BettingRoute: typeof BettingRoute
  BoxingRoute: typeof BoxingRouteWithChildren
  FaqRoute: typeof FaqRoute
  FaqsRoute: typeof FaqsRoute
  FavoritesRoute: typeof FavoritesRoute
  GameExitRoute: typeof GameExitRoute
  GamesRoute: typeof GamesRoute
  GeneralBettingRulesRoute: typeof GeneralBettingRulesRoute
  KycRoute: typeof KycRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  NotificationsRoute: typeof NotificationsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReceiptPreviewRoute: typeof ReceiptPreviewRoute
  SportsbettingRoute: typeof SportsbettingRouteWithChildren
  TennisRoute: typeof TennisRouteWithChildren
  TermsRoute: typeof TermsRoute
  UfcRoute: typeof UfcRouteWithChildren
  VideosRoute: typeof VideosRouteWithChildren
  WalletRoute: typeof WalletRouteWithChildren
  WalletTransactionStatusRoute: typeof WalletTransactionStatusRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthPhoneSignInRoute: typeof AuthPhoneSignInRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  GameGameIdRoute: typeof GameGameIdRoute
  IndexGameIdRoute: typeof IndexGameIdRoute
  IndexMatchesRoute: typeof IndexMatchesRoute
  PlayGameNameRoute: typeof PlayGameNameRoute
  PromotionsIdRoute: typeof PromotionsIdRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  PromotionsIndexRoute: typeof PromotionsIndexRoute
  IndexTournamentTournamentIdRoute: typeof IndexTournamentTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet-transaction-status': {
      id: '/wallet-transaction-status'
      path: '/wallet-transaction-status'
      fullPath: '/wallet-transaction-status'
      preLoaderRoute: typeof WalletTransactionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ufc': {
      id: '/ufc'
      path: '/ufc'
      fullPath: '/ufc'
      preLoaderRoute: typeof UfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis': {
      id: '/tennis'
      path: '/tennis'
      fullPath: '/tennis'
      preLoaderRoute: typeof TennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportsbetting': {
      id: '/sportsbetting'
      path: '/sportsbetting'
      fullPath: '/sportsbetting'
      preLoaderRoute: typeof SportsbettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-preview': {
      id: '/receipt-preview'
      path: '/receipt-preview'
      fullPath: '/receipt-preview'
      preLoaderRoute: typeof ReceiptPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-betting-rules': {
      id: '/general-betting-rules'
      path: '/general-betting-rules'
      fullPath: '/general-betting-rules'
      preLoaderRoute: typeof GeneralBettingRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-exit': {
      id: '/game-exit'
      path: '/game-exit'
      fullPath: '/game-exit'
      preLoaderRoute: typeof GameExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxing': {
      id: '/boxing'
      path: '/boxing'
      fullPath: '/boxing'
      preLoaderRoute: typeof BoxingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting': {
      id: '/betting'
      path: '/betting'
      fullPath: '/betting'
      preLoaderRoute: typeof BettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-history': {
      id: '/bet-history'
      path: '/bet-history'
      fullPath: '/bet-history'
      preLoaderRoute: typeof BetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/ufc/': {
      id: '/ufc/'
      path: '/'
      fullPath: '/ufc/'
      preLoaderRoute: typeof UfcIndexRouteImport
      parentRoute: typeof UfcRoute
    }
    '/tennis/': {
      id: '/tennis/'
      path: '/'
      fullPath: '/tennis/'
      preLoaderRoute: typeof TennisIndexRouteImport
      parentRoute: typeof TennisRoute
    }
    '/promotions/': {
      id: '/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof PromotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc/': {
      id: '/kyc/'
      path: '/'
      fullPath: '/kyc/'
      preLoaderRoute: typeof KycIndexRouteImport
      parentRoute: typeof KycRoute
    }
    '/boxing/': {
      id: '/boxing/'
      path: '/'
      fullPath: '/boxing/'
      preLoaderRoute: typeof BoxingIndexRouteImport
      parentRoute: typeof BoxingRoute
    }
    '/basketball/': {
      id: '/basketball/'
      path: '/'
      fullPath: '/basketball/'
      preLoaderRoute: typeof BasketballIndexRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/wallet/transactions': {
      id: '/wallet/transactions'
      path: '/transactions'
      fullPath: '/wallet/transactions'
      preLoaderRoute: typeof WalletTransactionsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/tennis/matches': {
      id: '/tennis/matches'
      path: '/matches'
      fullPath: '/tennis/matches'
      preLoaderRoute: typeof TennisMatchesRouteImport
      parentRoute: typeof TennisRoute
    }
    '/tennis/$Id': {
      id: '/tennis/$Id'
      path: '/$Id'
      fullPath: '/tennis/$Id'
      preLoaderRoute: typeof TennisIdRouteImport
      parentRoute: typeof TennisRoute
    }
    '/sportsbetting/$': {
      id: '/sportsbetting/$'
      path: '/$'
      fullPath: '/sportsbetting/$'
      preLoaderRoute: typeof SportsbettingSplatRouteImport
      parentRoute: typeof SportsbettingRoute
    }
    '/promotions/$id': {
      id: '/promotions/$id'
      path: '/promotions/$id'
      fullPath: '/promotions/$id'
      preLoaderRoute: typeof PromotionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameName': {
      id: '/play/$gameName'
      path: '/play/$gameName'
      fullPath: '/play/$gameName'
      preLoaderRoute: typeof PlayGameNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/$id': {
      id: '/notifications/$id'
      path: '/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof NotificationsIdRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/kyc/verify': {
      id: '/kyc/verify'
      path: '/verify'
      fullPath: '/kyc/verify'
      preLoaderRoute: typeof KycVerifyRouteImport
      parentRoute: typeof KycRoute
    }
    '/index/matches': {
      id: '/index/matches'
      path: '/index/matches'
      fullPath: '/index/matches'
      preLoaderRoute: typeof IndexMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/$gameId': {
      id: '/index/$gameId'
      path: '/index/$gameId'
      fullPath: '/index/$gameId'
      preLoaderRoute: typeof IndexGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-history/$ticketId': {
      id: '/bet-history/$ticketId'
      path: '/$ticketId'
      fullPath: '/bet-history/$ticketId'
      preLoaderRoute: typeof BetHistoryTicketIdRouteImport
      parentRoute: typeof BetHistoryRoute
    }
    '/basketball/matches': {
      id: '/basketball/matches'
      path: '/matches'
      fullPath: '/basketball/matches'
      preLoaderRoute: typeof BasketballMatchesRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/basketball/$Id': {
      id: '/basketball/$Id'
      path: '/$Id'
      fullPath: '/basketball/$Id'
      preLoaderRoute: typeof BasketballIdRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/phone-sign-in': {
      id: '/auth/phone-sign-in'
      path: '/auth/phone-sign-in'
      fullPath: '/auth/phone-sign-in'
      preLoaderRoute: typeof AuthPhoneSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis/tournament/$tournamentId': {
      id: '/tennis/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/tennis/tournament/$tournamentId'
      preLoaderRoute: typeof TennisTournamentTournamentIdRouteImport
      parentRoute: typeof TennisRoute
    }
    '/news/$slug/og': {
      id: '/news/$slug/og'
      path: '/og'
      fullPath: '/news/$slug/og'
      preLoaderRoute: typeof NewsSlugOgRouteImport
      parentRoute: typeof NewsSlugRoute
    }
    '/index/tournament/$tournamentId': {
      id: '/index/tournament/$tournamentId'
      path: '/index/tournament/$tournamentId'
      fullPath: '/index/tournament/$tournamentId'
      preLoaderRoute: typeof IndexTournamentTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball/tournament/$tournamentId': {
      id: '/basketball/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/basketball/tournament/$tournamentId'
      preLoaderRoute: typeof BasketballTournamentTournamentIdRouteImport
      parentRoute: typeof BasketballRoute
    }
  }
}

interface BasketballRouteChildren {
  BasketballIdRoute: typeof BasketballIdRoute
  BasketballMatchesRoute: typeof BasketballMatchesRoute
  BasketballIndexRoute: typeof BasketballIndexRoute
  BasketballTournamentTournamentIdRoute: typeof BasketballTournamentTournamentIdRoute
}

const BasketballRouteChildren: BasketballRouteChildren = {
  BasketballIdRoute: BasketballIdRoute,
  BasketballMatchesRoute: BasketballMatchesRoute,
  BasketballIndexRoute: BasketballIndexRoute,
  BasketballTournamentTournamentIdRoute: BasketballTournamentTournamentIdRoute,
}

const BasketballRouteWithChildren = BasketballRoute._addFileChildren(
  BasketballRouteChildren,
)

interface BetHistoryRouteChildren {
  BetHistoryTicketIdRoute: typeof BetHistoryTicketIdRoute
}

const BetHistoryRouteChildren: BetHistoryRouteChildren = {
  BetHistoryTicketIdRoute: BetHistoryTicketIdRoute,
}

const BetHistoryRouteWithChildren = BetHistoryRoute._addFileChildren(
  BetHistoryRouteChildren,
)

interface BoxingRouteChildren {
  BoxingIndexRoute: typeof BoxingIndexRoute
}

const BoxingRouteChildren: BoxingRouteChildren = {
  BoxingIndexRoute: BoxingIndexRoute,
}

const BoxingRouteWithChildren =
  BoxingRoute._addFileChildren(BoxingRouteChildren)

interface KycRouteChildren {
  KycVerifyRoute: typeof KycVerifyRoute
  KycIndexRoute: typeof KycIndexRoute
}

const KycRouteChildren: KycRouteChildren = {
  KycVerifyRoute: KycVerifyRoute,
  KycIndexRoute: KycIndexRoute,
}

const KycRouteWithChildren = KycRoute._addFileChildren(KycRouteChildren)

interface NewsSlugRouteChildren {
  NewsSlugOgRoute: typeof NewsSlugOgRoute
}

const NewsSlugRouteChildren: NewsSlugRouteChildren = {
  NewsSlugOgRoute: NewsSlugOgRoute,
}

const NewsSlugRouteWithChildren = NewsSlugRoute._addFileChildren(
  NewsSlugRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRouteWithChildren
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRouteWithChildren,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface NotificationsRouteChildren {
  NotificationsIdRoute: typeof NotificationsIdRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIdRoute: NotificationsIdRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface SportsbettingRouteChildren {
  SportsbettingSplatRoute: typeof SportsbettingSplatRoute
}

const SportsbettingRouteChildren: SportsbettingRouteChildren = {
  SportsbettingSplatRoute: SportsbettingSplatRoute,
}

const SportsbettingRouteWithChildren = SportsbettingRoute._addFileChildren(
  SportsbettingRouteChildren,
)

interface TennisRouteChildren {
  TennisIdRoute: typeof TennisIdRoute
  TennisMatchesRoute: typeof TennisMatchesRoute
  TennisIndexRoute: typeof TennisIndexRoute
  TennisTournamentTournamentIdRoute: typeof TennisTournamentTournamentIdRoute
}

const TennisRouteChildren: TennisRouteChildren = {
  TennisIdRoute: TennisIdRoute,
  TennisMatchesRoute: TennisMatchesRoute,
  TennisIndexRoute: TennisIndexRoute,
  TennisTournamentTournamentIdRoute: TennisTournamentTournamentIdRoute,
}

const TennisRouteWithChildren =
  TennisRoute._addFileChildren(TennisRouteChildren)

interface UfcRouteChildren {
  UfcIndexRoute: typeof UfcIndexRoute
}

const UfcRouteChildren: UfcRouteChildren = {
  UfcIndexRoute: UfcIndexRoute,
}

const UfcRouteWithChildren = UfcRoute._addFileChildren(UfcRouteChildren)

interface VideosRouteChildren {
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

interface WalletRouteChildren {
  WalletTransactionsRoute: typeof WalletTransactionsRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletTransactionsRoute: WalletTransactionsRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BasketballRoute: BasketballRouteWithChildren,
  BetHistoryRoute: BetHistoryRouteWithChildren,
  BettingRoute: BettingRoute,
  BoxingRoute: BoxingRouteWithChildren,
  FaqRoute: FaqRoute,
  FaqsRoute: FaqsRoute,
  FavoritesRoute: FavoritesRoute,
  GameExitRoute: GameExitRoute,
  GamesRoute: GamesRoute,
  GeneralBettingRulesRoute: GeneralBettingRulesRoute,
  KycRoute: KycRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  NotificationsRoute: NotificationsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReceiptPreviewRoute: ReceiptPreviewRoute,
  SportsbettingRoute: SportsbettingRouteWithChildren,
  TennisRoute: TennisRouteWithChildren,
  TermsRoute: TermsRoute,
  UfcRoute: UfcRouteWithChildren,
  VideosRoute: VideosRouteWithChildren,
  WalletRoute: WalletRouteWithChildren,
  WalletTransactionStatusRoute: WalletTransactionStatusRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthPhoneSignInRoute: AuthPhoneSignInRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  GameGameIdRoute: GameGameIdRoute,
  IndexGameIdRoute: IndexGameIdRoute,
  IndexMatchesRoute: IndexMatchesRoute,
  PlayGameNameRoute: PlayGameNameRoute,
  PromotionsIdRoute: PromotionsIdRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  PromotionsIndexRoute: PromotionsIndexRoute,
  IndexTournamentTournamentIdRoute: IndexTournamentTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
