import { OpenAPIHono } from "@hono/zod-openapi";
import affnookRoute from "./affnook";
import africastalkingDlrRoute from "./africastalking-dlr";
import basketballRoute from "./basketball";
import betHistoryRoute from "./bet-history";
import bonusRoute from "./bonus";
import bonusEngineCallbackRoute from "./bonus-engine-callbacks";
import bonusEngineReferenceDataRoute from "./bonus-engine-reference-data";
import casinoRoute from "./casino";
import casinoProviderRoute from "./casino-provider";
import cmsRoute from "./cms";
import filesRoute from "./files";
import footballRoute from "./football";
import gamesRoute from "./games";
import hallaRoute from "./halla";
import handoffRoute, { handoffPublicRoute } from "./handoff";
import hashcodexRoute from "./hashcodex";
import kudaRoute from "./kuda";
import kycRoute from "./kyc";
import lagosRushRoute from "./lagos-rush";
import loyaltyRoute from "./loyalty";
import missionRoute from "./mission";
import monnifyRoute from "./monnify";
import newsRoute from "./news";
import notificationsRoute from "./notifications";
import opayRoute from "./opay";
import phoneAuthRoute from "./phone-auth";
import pocketsRoute from "./pockets";
import scorpioRoute from "./scorpio";
import slotegratorRoute from "./slotegrator";
import swipegamesRoute from "./swipegames";
import sportsbookRoute from "./sportsbook";
import tennisRoute from "./tennis";
import thundrRoute from "./thundr";
import tournamentRoute from "./tournament";
import userRoute from "./user";
import walletRoute from "./wallet";
import webengageEventsRoute from "./webengage-events";
import palmpayRoute from "./palmpay";
import hellodutyRoute from "./helloduty";
import webengageSmsRoute from "./webengage-sms";

const routes = new OpenAPIHono();

routes.route("/affnook", affnookRoute);
routes.route("/football", footballRoute);
routes.route("/basketball", basketballRoute);
routes.route("/tennis", tennisRoute);
routes.route("/news", newsRoute);
routes.route("/notifications", notificationsRoute);
routes.route("/webhooks/webengage", webengageSmsRoute);
routes.route("/webhooks/helloduty", hellodutyRoute);
routes.route("/webengage", webengageEventsRoute);
routes.route("/webhooks/africastalking", africastalkingDlrRoute);
routes.route("/phone-auth", phoneAuthRoute);
routes.route("/wallet", walletRoute);
routes.route("/user", userRoute);
routes.route("/casino", casinoRoute);
routes.route("/lagos-rush", lagosRushRoute);
routes.route("/halla", hallaRoute);
routes.route("/pockets", pocketsRoute);
routes.route("/thndr", thundrRoute);
routes.route("/slotegrator", slotegratorRoute);
routes.route("/scorpio", scorpioRoute);
routes.route("/swipegames", swipegamesRoute);
routes.route("/sportsbook", sportsbookRoute);
routes.route("/account", casinoProviderRoute);
routes.route("/bills", monnifyRoute);
routes.route("/files", filesRoute);
routes.route("/games", gamesRoute);
routes.route("/handoff", handoffRoute);
routes.route("/public/handoff", handoffPublicRoute);
routes.route("/hashcodex", hashcodexRoute);
routes.route("/cms", cmsRoute);
routes.route("/kyc", kycRoute);
routes.route("/bet-history", betHistoryRoute);
routes.route("/opay", opayRoute);
routes.route("/kuda", kudaRoute);
routes.route("/palmpay", palmpayRoute);
routes.route("/loyalty", loyaltyRoute);
routes.route("/mission", missionRoute);
routes.route("/bonus", bonusRoute);
routes.route("/tournament", tournamentRoute);
routes.route(
	"/bem/api/BonusEngine/bonus-engine",
	bonusEngineReferenceDataRoute,
);
routes.route("/", bonusEngineCallbackRoute);

export default routes;
